import { usePreferences } from '@/app/PreferencesProvider'

const fa = {
  product: 'دیده‌بان جهان',
  prototype: 'نمونه نمایشی — داده‌ها واقعی نیستند',
  world: 'رصد جهان',
  developments: 'تحولات و پیش‌بینی',
  security: 'امنیت و ژئوپلیتیک',
  markets: 'اقتصاد و بازارها',
  countries: 'کشورها و مسیرها',
  reports: 'گزارش‌ها و تحلیل‌ها',
  data: 'مدیریت داده',
  search: 'جست‌وجوی سراسری',
  searchHint: 'رویداد، گزارش، کشور یا منبع…',
  organization: 'سازمان اطلس',
  sync: 'همگام‌سازی: ۲ دقیقه پیش',
  watchlist: 'ذخیره‌شده‌ها',
  notifications: 'اعلان‌ها',
  profile: 'پروفایل کاربر',
  geography: 'محدوده',
  global: 'جهان',
  time: 'بازه زمانی',
  domain: 'حوزه اطلاعاتی',
  allDomains: 'همه حوزه‌ها',
  sources: 'مجموعه منابع',
  verifiedSources: 'منابع منتخب',
  sourceCount: '۳۲ منبع',
  savedView: 'نمای ذخیره‌شده',
  dailyView: 'رصد روزانه',
  reset: 'پاک‌کردن فیلترها',
  editLayout: 'ویرایش چیدمان',
  finishEditing: 'پایان ویرایش',
  resetLayout: 'بازنشانی چیدمان',
  role: 'نقش آزمایشی',
  viewer: 'بیننده',
  orgAdmin: 'مدیر سازمان',
  dataManager: 'مدیر داده',
  devOnly: 'فقط برای نمایش نمونه',
  updated: 'به‌روزرسانی',
  sourceLabel: 'منبع',
  sourcesLabel: 'منابع',
  confidence: 'اطمینان تحلیل',
  fresh: 'تازه',
  cached: 'ذخیره‌شده',
  stale: 'قدیمی',
  partial: 'پوشش ناقص',
  empty: 'بدون داده',
  error: 'خطا',
  restricted: 'دسترسی محدود',
  loading: 'در حال بارگذاری',
  analyze: 'تحلیل با هوش مصنوعی',
  related: 'موارد مرتبط',
  collapse: 'جمع‌کردن',
  expand: 'تمام‌صفحه',
  more: 'گزینه‌های بیشتر',
  moveUp: 'جابه‌جایی به قبل',
  moveDown: 'جابه‌جایی به بعد',
  resize: 'تغییر اندازه',
  overview: 'نمای کلی',
  evidence: 'شواهد',
  aiAnalysis: 'تحلیل هوش مصنوعی',
  timeline: 'خط زمانی',
  inspectorSources: 'منابع',
  close: 'بستن',
  generated: 'محتوای تولیدشده با هوش مصنوعی',
  executiveSummary: 'خلاصه اجرایی',
  keyFindings: 'یافته‌های کلیدی',
  supporting: 'شواهد پشتیبان',
  contradictory: 'شواهد متناقض',
  assumptions: 'فرض‌ها',
  freshness: 'تازگی داده',
  diversity: 'تنوع منابع',
  limitations: 'محدودیت‌ها',
  relatedSignals: 'سیگنال‌های مرتبط',
  addToReport: 'افزودن به گزارش',
  rerun: 'اجرای دوبارهٔ تحلیل',
  restrictedTitle: 'این بخش برای نقش فعلی در دسترس نیست',
  restrictedBody: 'مدیریت منابع و پایش ورود داده فقط برای مدیر داده نمایش داده می‌شود.',
  noResults: 'نتیجه‌ای پیدا نشد',
  allResults: 'همه نتایج',
} as const

const en: Record<keyof typeof fa, string> = {
  product: 'Didehban Jahan',
  prototype: 'Demo prototype — data is not real',
  world: 'World Monitor',
  developments: 'Developments & Forecasts',
  security: 'Security & Geopolitics',
  markets: 'Economy & Markets',
  countries: 'Countries & Routes',
  reports: 'Reports & Analysis',
  data: 'Data Management',
  search: 'Global search',
  searchHint: 'Event, report, country, or source…',
  organization: 'Atlas Organization',
  sync: 'Synced 2 minutes ago',
  watchlist: 'Saved items',
  notifications: 'Notifications',
  profile: 'User profile',
  geography: 'Geography',
  global: 'Global',
  time: 'Time range',
  domain: 'Intelligence domain',
  allDomains: 'All domains',
  sources: 'Source set',
  verifiedSources: 'Selected sources',
  sourceCount: '32 sources',
  savedView: 'Saved view',
  dailyView: 'Daily watch',
  reset: 'Clear filters',
  editLayout: 'Edit layout',
  finishEditing: 'Finish editing',
  resetLayout: 'Reset layout',
  role: 'Prototype role',
  viewer: 'Viewer',
  orgAdmin: 'Organization admin',
  dataManager: 'Data manager',
  devOnly: 'Development demonstration only',
  updated: 'Updated',
  sourceLabel: 'source',
  sourcesLabel: 'sources',
  confidence: 'Analysis confidence',
  fresh: 'Fresh',
  cached: 'Cached',
  stale: 'Stale',
  partial: 'Partial coverage',
  empty: 'No data',
  error: 'Error',
  restricted: 'Restricted',
  loading: 'Loading',
  analyze: 'Analyze with AI',
  related: 'View related items',
  collapse: 'Collapse',
  expand: 'Fullscreen',
  more: 'More actions',
  moveUp: 'Move earlier',
  moveDown: 'Move later',
  resize: 'Resize',
  overview: 'Overview',
  evidence: 'Evidence',
  aiAnalysis: 'AI Analysis',
  timeline: 'Timeline',
  inspectorSources: 'Sources',
  close: 'Close',
  generated: 'AI-generated content',
  executiveSummary: 'Executive summary',
  keyFindings: 'Key findings',
  supporting: 'Supporting evidence',
  contradictory: 'Contradictory evidence',
  assumptions: 'Assumptions',
  freshness: 'Data freshness',
  diversity: 'Source diversity',
  limitations: 'Limitations',
  relatedSignals: 'Related signals',
  addToReport: 'Add to report',
  rerun: 'Re-run analysis',
  restrictedTitle: 'This area is unavailable for the current role',
  restrictedBody: 'Source operations and ingestion monitoring are visible only to data managers.',
  noResults: 'No results found',
  allResults: 'All results',
}

export function useProductCopy() {
  const { locale } = usePreferences()
  return locale === 'fa' ? fa : en
}

export type ProductCopy = Record<keyof typeof fa, string>
